# wrangler.toml
# Detta är konfigurationsfilen för Cloudflare Pages.
# Den talar om för Cloudflare hur man bygger och driftsätter projektet.
# Denna version använder den korrekta, platta strukturen.

name = "engrove-audio-toolkit-2-0"
pages_build_output_dir = "dist" # Anger den färdigbyggda mappen på toppnivå

# [build] är en separat sektion för byggrelaterade kommandon
[build]
command = "npm run build"
# wrangler.toml
