name = "engrove-audio"
compatibility_date = "2025-07-16"
pages_build_output_dir = "dist"

[[pages.functions]]
route = "/*"
exclude = [
  "/images/*",
  "/data/*",
  "/favicon.ico",
  "/sitemap.xml",
  "/robots.txt",
  "/og-image.png",
  "/LICENSE"
]
