# wrangler.toml
# Detta är konfigurationsfilen för Cloudflare Pages.
# Den talar om för Cloudflare hur man bygger och driftsätter projektet.

name = "engrove-audio-toolkit-2-0"
compatibility_date = "2024-07-25"

[pages]
# Anger vilken mapp som innehåller de färdigbyggda, statiska filerna.
# Vite bygger som standard till en mapp som heter "dist".
pages_build_output_dir = "dist"

# Anger vilket kommando som ska köras för att bygga projektet.
[pages.build]
command = "npm run build"
# wrangler.toml
