# wrangler.toml
# Detta är konfigurationsfilen för Cloudflare Pages.
# Denna version följer den korrekta syntaxen för Pages-projekt.

name = "engrove-audio-toolkit-2-0"
compatibility_date = "2024-07-25"

# All konfiguration specifik för Pages måste ligga under denna [pages] tabell.
[pages]
build_output_dir = "dist"
build_command = "npm run build"
# wrangler.toml
