# .github/workflows/ci.yml
# === SYFTE & ANSVAR ===
# Detta är den enda, konsoliderade CI/CD-pipelinen för projektet.
# Den ersätter de separata generate_context.yml och process_session_data.yml
# för att eliminera race conditions och garantera korrekt exekveringsordning.
#
# === ARBETSFLÖDE ===
# 1. Triggas vid push till relevanta filer (källkod, sessionsdata, dokumentation).
# 2. Bearbetar sessionsdata och uppdaterar dokumentationsfiler (t.ex. core_file_info.json) på runnern.
# 3. Genererar den fullständiga context.json baserat på det uppdaterade tillståndet.
# 4. Bygger och laddar upp GitHub Pages-artefakten (både index.html och det nya index2.html).
# 5. Committar de genererade dokumentationsfilerna tillbaka till repot med [skip ci].
# 6. Driftsätter den nya GitHub Pages-sajten.
#
# SYNTAX WARNING: Detta är fel: "name: STEP 3: Generate AI Context JSON", en deklaration får aldrig innehålla dubbla kolon ":"
#                 Detta är rätt syntax: "name: STEP 3 Generate AI Context JSON"
# PUSH TRIGGER: '.buildtrigger' ska vara den enda aktiva push triggern för att exakt styra när en körning ska ske. de övrika trigger objekten ska finnas knar men vara kommentarer.
# === HISTORIK ===
# * v1.0 (2025-08-13): Initial skapelse av Frankensteen. Konsoliderar två workflows.
# * v1.1 (2025-08-13): Korrigerat ett syntaxfel i cron-schemat (saknade citattecken).
# * v1.2 (2025-08-13): Refaktorerat session-bearbetning för att använda miljövariabler.
# * v1.3 (2025-08-13): (Help me God) Korrigerat YAML-parsingsfel genom att ta bort onödiga citattecken runt en miljövariabel.
# * v2.0 (2025-08-14): Korrigerat anropet till build_relations_graph.py för att inkludera project_overview JSON.
# * v2.1 (2025-08-15): Lade till 'push_options: --force' i auto-commit-steget för att hantera non-fast-forward-fel.
# * v2.2 (2025-08-15): Lade till byggsteg för det nya UI-verktyget (engrove_audio_tools_creator.py).
# * v2.3 (2025-08-16): Korrigerat anropet till engrove_audio_tools_creator.py för att använda det nya kommandobaserade API:et ('build-ui').
# * v2.4 (2025-08-16): (Help me God - Domslut) Lade till 'clean: true' till checkout-steget för att säkerställa en ren byggmiljö och eliminera potentiella cachningsproblem.
# * v2.5 (2025-08-17): (Help me God - Grundorsaksanalys) Lade till ett nytt steg för att skapa project_overview.json och korrigerade anropet till engrove_audio_tools_creator.py med det saknade argumentet.
# * v2.6 (2025-08-17): Lade till steg för att bygga Einstein RAG-index (ChromaDB), inklusive cachning.
# * v2.7 (2025-08-17): (Help me God - Domslut) Ersatt den bräckliga `printf`-metoden för JSON-konstruktion med en robust, direkt strängtilldelning för att lösa ett shell-parsingsfel.
# * v2.8 (2025-08-17): (Help me God - Domslut) Omarbetat RAG-indexeringen för att generera en portabel .json-fil istället för en ChromaDB-databas, vilket löser GitHubs filstorleksgräns.
# * v2.9 (2025-08-17): (Help me God - Domslut) Optimerat installationen av beroenden genom att installera en CPU-specifik version av torch för att dramatiskt minska installationstiden.
# * v2.10 (2025-08-17): (Help me God - Domslut) Korrigerat installationskommandot till att använda `--extra-index-url` för att inte exkludera PyPI, vilket löste installationsfelet.
# * v2.11 (2025-08-17): (Help me God - Domslut) Finaliserat RAG-pipelinen. Anropet till build_vector_index.py har uppdaterats och auto-commit-steget hanterar nu den komprimerade einstein_index.json.gz.
# * v2.12 (2025-08-17): (Engrove Mandate) Infört en manuell "strömbrytare" (.einstein) för att göra den tidskrävande RAG-indexeringen till en opt-in-process.
# * v2.13 (2025-08-17): (Help me God - Grundorsaksanalys) Korrigerat ett kritiskt fel där CI/CD misslyckades om `.einstein`-filen saknades. Commit-steget försöker inte längre committa den temporära trigger-filen och den raderas korrekt efter bygge.
# * v2.14 (2025-08-17): (Help me God - Domslut) Lade till ett villkorligt steg för att skapa en tom "dummy" `einstein_index.json.gz` när den riktiga indexeringen hoppas över. Detta löste ett 404-fel på klient-sidan.
# * v2.15 (2025-08-18): (Help me God - Domslut) Korrigerat grundorsaken till 404-felet. Säkerställer nu att `einstein_index.json.gz` (både äkta och dummy) alltid placeras i `dist/`-mappen före uppladdning.
# * v2.18 (2025-08-20): (Help me God - Grundorsaksanalys) Korrigerat `file_pattern` i commit-steget för att inkludera den nya `protocol_bundle.md`-artefakten istället för den föråldrade `.pbf.json`.
# * v3.1 (2025-08-22): (Frankensteen) Infört ett 'git pull'-steg för att tvinga synkronisering till main-branchens HEAD. Detta anpassar sig till operatörens workflow men offrar deterministisk spårbarhet.
# * v3.2 (2025-08-23): (Help me God - Domslut) Korrigerat den felaktiga argumentordningen till engrove_audio_tools_creator.py för att säkerställa att den fullständiga context.json används vid bygget av UI:t.
# * v3.3 (2025-08-29): Lagt till Node.js-installation, npm-installation samt migrerat SSM-generation till Node.js-skriptet generate-ssm.mjs.
# * SHA256_LF: UNVERIFIED
