name: Generate and Deploy AI Context Data

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.vue'
      - '**/*.html'
      - '**/*.md'
      - '.github/workflows/generate_context.yml'
      - 'requirements.txt'
      - 'docs/**.md'
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PYTHON_VERSION: '3.11'
  CONTEXT_FILE_JSON: 'context.json'
  CONTEXT_FILE_HTML: 'context.html'
  METADATA_FILE: 'metadata.json'
  SITE_DIR: '_site'

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    outputs:
      context-generated: ${{ steps.generate.outputs.success }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Prepare Output Directory
        run: mkdir -p ${{ env.SITE_DIR }}

      - name: Generate and Wrap Context Data
        id: generate
        run: |
          # Steg 1: Generera den råa JSON-datan
          if ! python scripts/generate_full_context.py > ${{ env.SITE_DIR }}/${{ env.CONTEXT_FILE_JSON }} 2> generation.log; then
            echo "[ERROR] Python-skriptet för kontextgenerering misslyckades. Se logg nedan:"
            cat generation.log
            echo "success=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "[INFO] Rå context.json genererades framgångsrikt."

          # Steg 2: Omsluta JSON i HTML med korrekt Python-indrag
          python - "${{ env.SITE_DIR }}" "${{ env.CONTEXT_FILE_JSON }}" "${{ env.CONTEXT_FILE_HTML }}" <<'EOF'
import sys
import json
from pathlib import Path

# Hämta argument
site_dir = Path(sys.argv[1])
json_file = sys.argv[2]
html_file = sys.argv[3]

json_path = site_dir / json_file
html_path = site_dir / html_file

html_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Context Data</title>
    <style>body { font-family: monospace; white-space: pre; word-wrap: break-word; }</style>
</head>
<body>
{json_content}
</body>
</html>"""

try:
    # Läs JSON-filen
    with open(json_path, 'r', encoding='utf-8') as f:
        json_content = f.read()

    # Skapa HTML-fil
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_template.format(json_content=json_content))

    print(f'[INFO] Omslutning av JSON i HTML lyckades: {html_path}')
except Exception as e:
    print(f'[ERROR] Misslyckades att omsluta JSON i HTML: {e}', file=sys.stderr)
    sys.exit(1)
EOF

          # Slutgiltig kontroll
          if [ -f "${{ env.SITE_DIR }}/${{ env.CONTEXT_FILE_HTML }}" ]; then
            echo "[INFO] context.html skapad. Byggsteget lyckades."
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "[ERROR] context.html skapades inte. Byggsteget misslyckades."
            echo "success=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Create Metadata
        if: steps.generate.outputs.success == 'true'
        run: |
          cat > ${{ env.SITE_DIR }}/${{ env.METADATA_FILE }} <<EOF
          {
            "generated_at": "$(date -Iseconds)",
            "workflow_run_id": "${{ github.run_id }}",
            "commit_sha": "${{ github.sha }}",
            "repository": "${{ github.repository }}"
          }
          EOF
          echo "[INFO] metadata.json skapad."

      - name: Upload Pages Artifact
        if: steps.generate.outputs.success == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.SITE_DIR }}

  deploy:
    needs: validate-and-build
    if: needs.validate-and-build.outputs.context-generated == 'true'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
