# .github/workflows/generate_context.yml
#
# HISTORIK:
# * v1.0 - v8.0: Tidigare versioner.
# * v9.0 (Help me God Audit): Total refaktorisering. Publicerar nu rå JSON istället för HTML
#   för att säkerställa att AI-modeller kan processa datan direkt och robust.
#
# TILLÄMPADE REGLER (Frankensteen v3.7):
# - Robust felhantering med explicit validering i varje kritiskt steg.
# - Prestanda-optimering genom cachning.
# - Säkerhet genom minimala behörigheter och säker tokenhantering.
# - Observabilitet genom strukturerad loggning.

name: Generate and Deploy AI Context Data

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.vue'
      - '**/*.html'
      - '**/*.md'
      - '.github/workflows/generate_context.yml'
      - 'requirements.txt'
      - 'docs/**.md'
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PYTHON_VERSION: '3.11'
  CONTEXT_FILE: 'context.json'
  METADATA_FILE: 'metadata.json'
  SITE_DIR: '_site'

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    outputs:
      context-generated: ${{ steps.generate.outputs.success }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Prepare Output Directory
        run: mkdir -p ${{ env.SITE_DIR }}

      - name: Generate Context JSON
        id: generate
        run: |
          if python scripts/generate_full_context.py > ${{ env.SITE_DIR }}/${{ env.CONTEXT_FILE }} 2> generation.log; then
            echo "success=true" >> $GITHUB_OUTPUT
            echo "[INFO] context.json genererades framgångsrikt."
          else
            echo "[ERROR] Misslyckades med att generera context.json. Se logg nedan:"
            cat generation.log
            echo "success=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Metadata
        if: steps.generate.outputs.success == 'true'
        run: |
          cat > ${{ env.SITE_DIR }}/${{ env.METADATA_FILE }} << EOF
          {
            "generated_at": "$(date -Iseconds)",
            "workflow_run_id": "${{ github.run_id }}",
            "commit_sha": "${{ github.sha }}",
            "repository": "${{ github.repository }}"
          }
          EOF
          echo "[INFO] metadata.json skapad."

      - name: Upload Pages Artifact
        if: steps.generate.outputs.success == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.SITE_DIR }}

  deploy:
    needs: validate-and-build
    if: needs.validate-and-build.outputs.context-generated == 'true'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
