# .github/workflows/process_historical_sessions.yml

name: Process Historical Session Data

on:
  # Körs automatiskt när du pushar nya/ändrade filer till sessions-mappen
  push:
    branches: [ "main" ]
    paths:
      - 'sessions/**.json'
      - '.github/workflows/process_historical_sessions.yml'

  # Tillåter dig att köra detta workflow manuellt från "Actions"-fliken på GitHub
  workflow_dispatch:

# Sätter behörigheter för GITHUB_TOKEN för att tillåta att workflowet
# checkar in ändringar till din repository.
permissions:
  contents: write

jobs:
  build-and-commit-history:
    runs-on: ubuntu-latest

    steps:
      # Steg 1: Checka ut din repository så att vi har tillgång till skript och filer
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Steg 2: Sätt upp Python 3.11-miljön
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      # Steg 3: Kör ditt Python-skript för att bygga de konsoliderade filerna
      - name: Run Historical Reconstruction Builder
        run: |
          python scripts/history/historical_reconstruction_builder.py sessions/ .
        # Argument 1: 'sessions/' är mappen med indata-JSON.
        # Argument 2: '.' är rot-mappen för utdata (dvs. skriptet skapar docs/ och tools/ här).

      # Steg 4: Konfigurera Git och checka in de genererade filerna
      - name: Commit and Push Changes
        run: |
          # Konfigurera Git med en bot-användare
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Kontrollera om det finns några filer att checka in
          if ! git diff --quiet --exit-code docs/ tools/; then
            echo "Ändringar upptäcktes. Förbereder att checka in..."
            # Lägg till de specifika filerna som genererats
            git add docs/ByggLogg.json
            git add docs/Chatthistorik.json
            git add docs/ai_protocol_performance.json
            git add tools/frankensteen_learning_db.json

            # Skapa ett commit-meddelande
            git commit -m "Chore: Update historical data from session logs" -m "Detta commit har genererats automatiskt av process_historical_sessions.yml workflow."

            # Pusha ändringarna tillbaka till 'main'-branchen
            git push
          else
            echo "Inga ändringar att checka in."
          fi
